<script setup>
import { Search, ArrowRight, FolderSearch, MapPin, Scale } from '@lucide/vue';
import { useForm, Link } from '@inertiajs/vue3';

const props = defineProps({ expedienteQuery: String, casesList: Array });
const form = useForm({ expediente: props.expedienteQuery || '' });
const submitSearch = () => form.get(route('cases.index'), { preserveState: true });
</script>

<template>
    <main class="min-h-screen bg-[#f4f7f6] text-slate-900">
        <div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
            <section class="overflow-hidden rounded-2xl bg-slate-900 shadow-xl shadow-slate-900/10">
                <div class="grid gap-8 px-6 py-10 sm:px-10 lg:grid-cols-[1fr_420px] lg:items-center lg:px-14 lg:py-14">
                    <div class="text-white"><div class="mb-5 flex size-12 items-center justify-center rounded-xl bg-emerald-400 text-slate-950"><FolderSearch class="size-6" /></div><p class="text-xs font-bold uppercase tracking-[0.2em] text-emerald-300">MP-IA · Gestión ministerial</p><h1 class="mt-3 max-w-xl text-3xl font-bold tracking-tight sm:text-4xl">Consulta tu carpeta de investigación</h1><p class="mt-4 max-w-lg text-sm leading-6 text-slate-300">Localiza un expediente para revisar sus datos y solicitar un análisis jurídico asistido por inteligencia artificial.</p></div>
                    <form @submit.prevent="submitSearch" class="rounded-xl bg-white p-5 shadow-2xl"><label for="expediente" class="text-sm font-bold text-slate-800">Número de expediente</label><div class="relative mt-3"><Search class="pointer-events-none absolute left-3 top-1/2 size-5 -translate-y-1/2 text-slate-400" /><input id="expediente" v-model="form.expediente" type="text" placeholder="Ej. 00031/2025" required class="w-full rounded-lg border border-slate-200 py-3 pl-11 pr-4 text-sm outline-none transition placeholder:text-slate-400 focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10" /></div><button type="submit" :disabled="form.processing" class="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-3 text-sm font-bold text-white transition hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-50"><Search class="size-4" /> {{ form.processing ? 'Buscando...' : 'Buscar expediente' }}</button></form>
                </div>
            </section>

            <section v-if="casesList.length > 0" class="mt-8">
                <div class="mb-4 flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p class="text-xs font-bold uppercase tracking-wider text-emerald-600">Resultados de búsqueda</p><h2 class="mt-1 text-2xl font-bold">{{ casesList.length }} carpeta{{ casesList.length === 1 ? '' : 's' }} encontrada{{ casesList.length === 1 ? '' : 's' }}</h2></div><p class="text-sm text-slate-500">Coincidencia: <span class="font-bold text-slate-700">{{ expedienteQuery }}</span></p></div>
                <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="hidden overflow-x-auto md:block"><table class="w-full text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-[11px] uppercase tracking-wider text-slate-500"><tr><th class="px-6 py-4">Carpeta</th><th class="px-6 py-4">Delito</th><th class="px-6 py-4">Ubicación</th><th class="px-6 py-4">Estado</th><th class="px-6 py-4 text-right">Acción</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="item in casesList" :key="item.ID_CARPETA" class="transition hover:bg-emerald-50/30"><td class="px-6 py-4"><p class="font-bold text-slate-800">{{ item.TIPO }} #{{ item.ID_CARPETA }}</p><p class="mt-1 text-xs text-slate-400">{{ item.EXPEDIENTE }}</p></td><td class="px-6 py-4"><p class="font-semibold text-slate-700">{{ item.DELITO }}</p><p class="text-xs text-slate-500">{{ item.MODALIDAD }}</p></td><td class="px-6 py-4 text-slate-600"><span class="inline-flex items-center gap-1"><MapPin class="size-3.5 text-emerald-600" /> {{ item.UNIDAD }} · {{ item.MUNICIPIO }}</span></td><td class="px-6 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{{ item.ESTADO }}</span></td><td class="px-6 py-4 text-right"><Link :href="route('cases.show', { expediente: encodeURIComponent(item.EXPEDIENTE), idCarpeta: item.ID_CARPETA })" class="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white transition hover:bg-emerald-700">Abrir análisis <ArrowRight class="size-3.5" /></Link></td></tr></tbody></table></div><div class="divide-y divide-slate-100 md:hidden"><article v-for="item in casesList" :key="item.ID_CARPETA" class="p-5"><div class="flex items-start justify-between gap-3"><div><p class="font-bold">{{ item.TIPO }} #{{ item.ID_CARPETA }}</p><p class="mt-1 text-xs text-slate-400">{{ item.EXPEDIENTE }}</p></div><span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{{ item.ESTADO }}</span></div><p class="mt-4 text-sm font-semibold text-slate-700"><Scale class="mr-1 inline size-4 text-emerald-600" />{{ item.DELITO }}</p><p class="mt-1 text-xs text-slate-500">{{ item.MODALIDAD }} · {{ item.UNIDAD }} · {{ item.MUNICIPIO }}</p><Link :href="route('cases.show', { expediente: encodeURIComponent(item.EXPEDIENTE), idCarpeta: item.ID_CARPETA })" class="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-slate-900 px-3 py-2.5 text-xs font-bold text-white">Abrir análisis <ArrowRight class="size-3.5" /></Link></article></div></div>
            </section>
            <section v-else-if="expedienteQuery" class="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><FolderSearch class="mx-auto size-9 text-slate-300" /><h2 class="mt-4 text-lg font-bold">No encontramos coincidencias</h2><p class="mt-2 text-sm text-slate-500">Revisa el número de expediente e inténtalo nuevamente.</p></section>
        </div>
    </main>
</template>
